/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ionic_Msmq_Queue */

#ifndef _Included_ionic_Msmq_Queue
#define _Included_ionic_Msmq_Queue
#ifdef __cplusplus
extern "C" {
#endif
#undef ionic_Msmq_Queue_AccessReceive
#define ionic_Msmq_Queue_AccessReceive 1L
#undef ionic_Msmq_Queue_AccessSend
#define ionic_Msmq_Queue_AccessSend 2L
#undef ionic_Msmq_Queue_AccessPeek
#define ionic_Msmq_Queue_AccessPeek 32L
#undef ionic_Msmq_Queue_AccessAdmin
#define ionic_Msmq_Queue_AccessAdmin 128L
#undef ionic_Msmq_Queue_TimeoutInfinte
#define ionic_Msmq_Queue_TimeoutInfinte -1L
/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeCreateQueue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeCreateQueue
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeDeleteQueue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeDeleteQueue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeOpenQueueWithAccess
 * Signature: ([JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeOpenQueueWithAccess
  (JNIEnv *, jobject, jlongArray, jstring, jint);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeReceive
 * Signature: ([JLionic/Msmq/Message;ZIZ)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeReceive
  (JNIEnv *, jobject, jlongArray, jobject, jboolean, jint, jboolean);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeSend
 * Signature: ([JLionic/Msmq/Message;Z)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeSend
  (JNIEnv *, jobject, jlongArray, jobject, jboolean);

/*
 * Class:     ionic_Msmq_Queue
 * Method:    nativeClose
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_ionic_Msmq_Queue_nativeClose
  (JNIEnv *, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
